version: "3.9"

services:
  postgres:
    image: postgres:16-alpine
    container_name: bank-postgres
    restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init-multi-db.sh:/docker-entrypoint-initdb.d/init-multi-db.sh:ro

  auth:
    build:
      context: .
      dockerfile: services/auth/Dockerfile
    container_name: bank-auth-service
    depends_on:
      - migrate-auth
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST: postgres
      CONFIG_PATH: "/config/local.yaml"
    ports:
      - "8080:8080"
    restart: unless-stopped

  migrate-auth:
    image: migrate/migrate
    depends_on:
      - postgres
    volumes:
      - ./services/auth/migrations:/migrations
    command:
      [
        "-path", "/migrations",
        "-database", "postgres://postgres:postgres@postgres:5432/auth?sslmode=disable",
        "up"
      ]
    restart: on-failure

  account:
    build:
      context: .
      dockerfile: services/account/Dockerfile
    container_name: bank-account-service
    depends_on:
      - migrate-account
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST: postgres
      CONFIG_PATH: "/config/local.yaml"
    ports:
      - "8082:8082"
    restart: unless-stopped

  migrate-account:
    image: migrate/migrate
    depends_on:
      - postgres
    volumes:
      - ./services/account/migrations:/migrations
    command:
      [
        "-path", "/migrations",
        "-database", "postgres://postgres:postgres@postgres:5432/account?sslmode=disable",
        "up"
      ]
    restart: on-failure

  kafka:
    image: confluentinc/cp-kafka:7.6.1
    container_name: kafka
    healthcheck:
      test: [ "CMD", "kafka-topics", "--bootstrap-server", "localhost:9092", "--list" ]
      interval: 10s
      timeout: 5s
      retries: 10
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    ports:
      - "29092:29092"

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    ports:
      - "8081:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092

  zookeeper:
    image: confluentinc/cp-zookeeper:7.6.1
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

volumes:
  pgdata: