env: "dev"
dbUrl: "postgres://postgres:postgres@postgres:5432/bank?sslmode=disable"
port: 8082
jwt-secret: "supersecretkey"
#dbUrl: "postgres://postgres:postgres@localhost:5432/bank?sslmode=disable"

# Integrations
auth_service:
  host: "bank-auth-service"
  port: 8080
